# Generated by Django 4.2.10 on 2024-02-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_item_options_alter_item_name_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(help_text='Указывается цена в центах', verbose_name='Цена'),
        ),
    ]
