# Generated by Django 4.2.10 on 2024-02-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_order_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
