# Generated by Django 4.2.10 on 2024-02-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_remove_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='currency',
        ),
    ]
